export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const MAIL_SENDING = 'MAIL_SENDING';
export const MAIL_SEND_SUCCESS = 'MAIL_SEND_SUCCESS';
export const HIDE_SUCCESS_MESSAGE = 'HIDE_SUCCESS_MESSAGE'